@startuml Delete User
skin rose
scale 3

|User|
start
:Select "Delete" in user row;
|User Interface|
:Display confirmation prompt;
|User|
:Confirm deletion;
|User Interface|
:Send deletion request;
|System|
:Handle delete account request;
:Delete account information;
:Return delete success;
|User Interface|
:Display success message;
:Get updated user list;
stop
@enduml