@startuml Create Delivery Order
skin rose
scale 3

|User|
start
:Select "Create Delivery Order";
|User Interface|
:Display form;
|User|
:Enter delivery details;
:Select related order (Sale/Purchase);
:Click "Create";
|User Interface|
:Validate form;
:Send request to system;
|System|
:Handle add delivery order request;
:Validate details;
if (Valid?) then (yes)
  :Save delivery order information;
  :Return add success;
  |User Interface|
  :Display success message;
  :Get updated delivery order list;
else (no)
  |System|
  :Return validation failure;
  |User Interface|
  :Display error message;
endif
stop

@enduml