@startuml Create Product
skin rose
scale 3

|User|
start
:Select "Create Product";
|User Interface|
:Display form;
|User|
:Enter product details;
:Click "Create";
|User Interface|
:Validate form;
:Send request to system;
|System|
:Handle add product request;
:Validate details;
if (Valid?) then (yes)
  :Save product information;
  :Return add success;
  |User Interface|
  :Display success message;
  :Get updated product list;
else (no)
  |System|
  :Return validation failure;
  |User Interface|
  :Display error message;
endif
stop

@enduml