@startuml Create Vehicle
skin rose
scale 3

|User|
start
:Select Partner;
:Click "Add Vehicle";
|User Interface|
:Display vehicle form;
|User|
:Enter vehicle details;
:Click "Create";
|User Interface|
:Validate form;
:Send request to system;
|System|
:Handle add vehicle request;
:Validate details;
if (Valid?) then (yes)
  :Save vehicle information;
  :Return add success;
  |User Interface|
  :Display success message;
  :Show updated partner details with new vehicle;
else (no)
  |System|
  :Return validation failure;
  |User Interface|
  :Display error message;
endif
stop

@enduml